create table
  public."Appointment" (
    "appointmentId" bigint generated by default as identity not null,
    "patientID" bigint not null,
    clinic text null,
    "scheduledTime" text not null,
    "Priority" smallint null,
    "Finished" boolean null default false,
    "checkedIn" boolean null default false,
    "roomNumber" integer null,
    "doctorID" bigint null,
    "doctorName" text null,
    "patientName" text null,
    "AppDate" date null,
    "PatientEmail" text null,
    "PatientPhone" text null,
    entered boolean not null default false,
    "enterTime" time without time zone null,
    "checkInTime" time without time zone null,
    "finishTime" time without time zone null,
    constraint Appointment_pkey primary key ("appointmentId", "patientID", "scheduledTime"),
    constraint Appointment_appointmentId_key unique ("appointmentId"),
    constraint Appointment_doctorID_fkey foreign key ("doctorID") references "DocInfo" ("DocID"),
    constraint Appointment_patientID_fkey foreign key ("patientID") references "Patient" ("patientID")
  ) tablespace pg_default;

  create table
  public."DocInfo" (
    "DocID" bigint generated by default as identity not null,
    "Name" text null,
    "Email" text null,
    "Clinic" text null,
    "AppNum" bigint null default '0'::bigint,
    "RoomNumber" bigint null,
    constraint DocInfo_pkey primary key ("DocID"),
    constraint DocInfo_DocID_key unique ("DocID")
  ) tablespace pg_default;

  create table
  public."Patient" (
    "patientID" bigint generated by default as identity not null,
    name text null,
    email text null,
    "ContactNumber" text null,
    constraint Patient_pkey primary key ("patientID"),
    constraint Patient_patientID_key unique ("patientID")
  ) tablespace pg_default;

  create table
  public."Receptionist" (
    "receptionistID" bigint generated by default as identity not null,
    name text null,
    email text null,
    "ContactNumber" text null,
    constraint Receptionist_pkey primary key ("receptionistID"),
    constraint Receptionist_patientID_key unique ("receptionistID")
  ) tablespace pg_default;